homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  internal_url: http://home-assistant.local:80
  packages: !include_dir_named include

history:
mobile_app:
sun:
system_health:
recorder:

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/bar-card/bar-card.js
      type: module

    - url: /hacsfiles/button-card/button-card.js
      type: module

    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module

    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: js

    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module

    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module

    - url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js
      type: module

    - url: /hacsfiles/lovelace-hui-element/hui-element.js
      type: module

    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module

    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module

    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module

    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module

    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module

    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module

    - url: /local/calendar-card.js?v=31091
      type: module

    - url: /local/valetudo-map-card.js?v=42dbceb
      type: js

    - url: /local/custom_icons.js?v=25052001
      type: module

    - url: /local/font.css
      type: css

person:
  - name: Bob
    id: bob_4343cded-1d6d-4b1d-89b3-92a302348d3a
    user_id: efa2bc58b0f547baa84cc2ddc123cd56
    device_trackers:
      - device_tracker.bobs_iphone
      - device_tracker.bobs_phone
      - device_tracker.bobs_watch

  - name: Kimberly
    id: kimberly_c2c568e8-a00d-4c54-90af-70859b436cae
    device_trackers:
      - device_tracker.kimberly_iphone
      - device_tracker.kimberly_phone

hacs:
  token: !secret hacs_token

tradfri:
  host: !secret tradfri_host

light:
  - platform: group
    name: Woonkamer
    entities:
      - light.woonkamer_tv
      - light.woonkamer_secretaire

  - platform: group
    name: Werkkamer
    entities:
      - light.werkkamer_plafond

  - platform: group
    name: Slaapkamer
    entities:
      - light.slaapkamer_bob
      - light.slaapkamer_kimberly

pi_hole:
  - host: !secret pi_hole_host

homekit:
  ip_address: !secret homekit_ip_address
  filter:
    include_domains:
      - light
      - scene
